import { BsBackpack3Fill } from "react-icons/bs";
import { BsBagHeart } from "react-icons/bs";
import { BsBinocularsFill } from "react-icons/bs";
import { CgBot } from "react-icons/cg";
import { FiCodesandbox } from "react-icons/fi";
import { FiCpu } from "react-icons/fi";

export const mockLevels = [
  {
    id: 1,
    icon: <BsBackpack3Fill />,
    w: 30,
    b: 20,
    g: 5,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 2,
    icon: <BsBagHeart />,
    w: 40,
    b: 30,
    g: 7,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 3,
    icon: <BsBinocularsFill />,
    w: 50,
    b: 40,
    g: 9,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 4,
    icon: <CgBot />,
    w: 60,
    b: 50,
    g: 11,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 5,
    icon: <FiCodesandbox />,
    w: 70,
    b: 75,
    g: 13,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 6,
    icon: <FiCpu />,
    w: 80,
    b: 85,
    g: 15,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 7,
    icon: <BsBackpack3Fill />,
    w: 80,
    b: 95,
    g: 17,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 8,
    icon: <BsBagHeart />,
    w: 80,
    b: 105,
    g: 19,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 9,
    icon: <BsBinocularsFill />,
    w: 80,
    b: 110,
    g: 21,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 10,
    icon: <CgBot />,
    w: 90,
    b: 115,
    g: 23,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 11,
    icon: <FiCodesandbox />,
    w: 90,
    b: 125,
    g: 15,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 12,
    icon: <FiCpu />,
    w: 90,
    b: 135,
    g: 15,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 13,
    icon: <BsBagHeart />,
    w: 90,
    b: 145,
    g: 15,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
  {
    id: 14,
    icon: <BsBinocularsFill />,
    w: 90,
    b: 155,
    g: 15,
    completed: false,
    gemsCollected: 0,
    points: 0,
  },
];
